export const SET_LISTS = 'SET_LISTS';
export const LISTS_ERROR = 'LISTS_ERROR';
export const LISTS_REQUEST = 'LISTS_REQUEST';

export const SET_DETAILS = 'SET_DETAILS';
export const DETAILS_ERROR = 'DETAILS_ERROR';
export const DETAILS_REQUEST = 'DETAILS_REQUEST';

export const SET_AUTH = 'SET_AUTH';
export const DEL_AUTH = 'DEL_AUTH';

export const ACCOUNT_DETAILS_REQUEST = 'ACCOUNT_DETAILS_REQUEST';
export const ACCOUNT_DETAILS_SUCCESS = 'ACCOUNT_DETAILS_SUCCESS';
export const ACCOUNT_DETAILS_FAILURE = 'ACCOUNT_DETAILS_FAILURE';

export const RATED_REQUEST = 'RATED_REQUEST';
export const RATED_SUCCESS = 'RATED_SUCCESS';
export const RATED_FAILURE = 'RATED_FAILURE';

export const FAVORITES_SUCCESS = 'FAVORITES_SUCCESS';
export const FAVORITES_REQUEST = 'FAVORITES_REQUEST';
export const FAVORITES_FAILURE = 'FAVORITES_FAILURE';

export const SUBMIT_RATING_REQUEST = 'SUBMIT_RATING_REQUEST';
export const SUBMIT_RATING_SUCCESS = 'SUBMIT_RATING_SUCCESS';
export const SUBMIT_RATING_FAILURE = 'SUBMIT_RATING_FAILURE';

export const ADD_BOOKMARK_SUCCESS = 'ADD_BOOKMARK_SUCCESS';
export const ADD_BOOKMARK_REQUEST = 'ADD_BOOKMARK_REQUEST';
export const ADD_BOOKMARK_FAILURE = 'ADD_BOOKMARK_FAILURE';

export const ADD_FAVORITE_REQUEST = 'ADD_FAVORITE_REQUEST';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const ADD_FAVORITE_FAILURE = 'ADD_FAVORITE_FAILURE';
