export const LISTS_SUCCESS = 'LISTS_SUCCESS';
export const LISTS_ERROR = 'LISTS_ERROR';
export const LISTS_REQUEST = 'LISTS_REQUEST';

export const DETAILS_SUCCESS = 'DETAILS_SUCCESS';
export const DETAILS_ERROR = 'DETAILS_ERROR';
export const DETAILS_REQUEST = 'DETAILS_REQUEST';

export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS';
export const TOKEN_FAILURE = 'TOKEN_FAILURE';

export const SESSION_REQUEST = 'SESSION_REQUEST';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SESSION_FAILURE = 'SESSION_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ACCOUNT_INFO_REQUEST = 'ACCOUNT_INFO_REQUEST';
export const ACCOUNT_INFO_SUCCESS = 'ACCOUNT_INFO_SUCCESS';
export const ACCOUNT_INFO_FAILURE = 'ACCOUNT_INFO_FAILURE';

export const RATED_REQUEST = 'RATED_REQUEST';
export const RATED_SUCCESS = 'RATED_SUCCESS';
export const RATED_FAILURE = 'RATED_FAILURE';

export const FAVORITES_SUCCESS = 'FAVORITES_SUCCESS';
export const FAVORITES_REQUEST = 'FAVORITES_REQUEST';
export const FAVORITES_FAILURE = 'FAVORITES_FAILURE';

export const SUBMIT_RATING_REQUEST = 'SUBMIT_RATING_REQUEST';
export const SUBMIT_RATING_SUCCESS = 'SUBMIT_RATING_SUCCESS';
export const SUBMIT_RATING_FAILURE = 'SUBMIT_RATING_FAILURE';

export const ADD_BOOKMARK_SUCCESS = 'ADD_BOOKMARK_SUCCESS';
export const ADD_BOOKMARK_REQUEST = 'ADD_BOOKMARK_REQUEST';
export const ADD_BOOKMARK_FAILURE = 'ADD_BOOKMARK_FAILURE';

export const ADD_FAVORITE_REQUEST = 'ADD_FAVORITE_REQUEST';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const ADD_FAVORITE_FAILURE = 'ADD_FAVORITE_FAILURE';
